objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    certificate:
      description: Certificate operations for PowerStore Storage System
      name: certificate
      namespace: ''
      version_added: 1.4.0
    cluster:
      description: Manage cluster related operations on PowerStore
      name: cluster
      namespace: ''
      version_added: 1.3.0
    dns:
      description: DNS operations on a PowerStore storage system
      name: dns
      namespace: ''
      version_added: 1.5.0
    email:
      description: Destination Email operations on a PowerStore storage system
      name: email
      namespace: ''
      version_added: 1.5.0
    file_dns:
      description: Manage File DNS for PowerStore
      name: file_dns
      namespace: ''
      version_added: 3.1.0
    file_interface:
      description: Manage File interface for PowerStore
      name: file_interface
      namespace: ''
      version_added: 3.1.0
    file_nis:
      description: Manage File NIS for PowerStore
      name: file_nis
      namespace: ''
      version_added: 3.1.0
    filesystem:
      description: Filesystem operations for PowerStore Storage system
      name: filesystem
      namespace: ''
      version_added: 1.1.0
    filesystem_snapshot:
      description: Manage Filesystem Snapshots for PowerStore
      name: filesystem_snapshot
      namespace: ''
      version_added: 1.1.0
    host:
      description: Manage host on PowerStore storage system
      name: host
      namespace: ''
      version_added: 1.0.0
    hostgroup:
      description: Manage host group on PowerStore Storage System
      name: hostgroup
      namespace: ''
      version_added: 1.0.0
    info:
      description: Gathers information about PowerStore Storage entities
      name: info
      namespace: ''
      version_added: 1.0.0
    job:
      description: Manage jobs for PowerStore
      name: job
      namespace: ''
      version_added: 1.3.0
    ldap_account:
      description: Manage LDAP Account for PowerStore
      name: ldap_account
      namespace: ''
      version_added: 1.6.0
    ldap_domain:
      description: Manage LDAP domain for PowerStore
      name: ldap_domain
      namespace: ''
      version_added: 1.6.0
    local_user:
      description: Local user operations for PowerStore Storage System
      name: local_user
      namespace: ''
      version_added: 1.3.0
    nasserver:
      description: NAS Server operations for PowerStore Storage system
      name: nasserver
      namespace: ''
      version_added: 1.1.0
    network:
      description: Manage networks for PowerStore
      name: network
      namespace: ''
      version_added: 1.3.0
    nfs:
      description: Manage NFS exports for PowerStore
      name: nfs
      namespace: ''
      version_added: 1.1.0
    nfs_server:
      description: Manage NFS server for PowerStore
      name: nfs_server
      namespace: ''
      version_added: 3.1.0
    ntp:
      description: NTP operations on a PowerStore storage system
      name: ntp
      namespace: ''
      version_added: 1.5.0
    protectionpolicy:
      description: Perform Protection policy operations for PowerStore storage system
      name: protectionpolicy
      namespace: ''
      version_added: 1.0.0
    quota:
      description: Manage Tree Quotas and User Quotas on PowerStore
      name: quota
      namespace: ''
      version_added: 1.1.0
    remote_support:
      description: Remote Support operations on a PowerStore storage system
      name: remote_support
      namespace: ''
      version_added: 1.5.0
    remote_support_contact:
      description: Remote Support Contact operations on a PowerStore storage system
      name: remote_support_contact
      namespace: ''
      version_added: 1.5.0
    remotesystem:
      description: Remote system operations on a PowerStore storage system
      name: remotesystem
      namespace: ''
      version_added: 1.4.0
    replicationrule:
      description: Replication rule operations on a PowerStore storage system
      name: replicationrule
      namespace: ''
      version_added: 1.2.0
    replicationsession:
      description: Replication session operations on a PowerStore storage system
      name: replicationsession
      namespace: ''
      version_added: 1.2.0
    role:
      description: Get details of the roles present on the PowerStore storage system
      name: role
      namespace: ''
      version_added: 1.3.0
    security_config:
      description: Security configuration operations for PowerStore Storage System
      name: security_config
      namespace: ''
      version_added: 1.4.0
    service_config:
      description: Manage Service config on PowerStore storage systems
      name: service_config
      namespace: ''
      version_added: 3.1.0
    smb_server:
      description: Manage SMB server for PowerStore
      name: smb_server
      namespace: ''
      version_added: 3.1.0
    smbshare:
      description: Manage SMB shares on a PowerStore storage system
      name: smbshare
      namespace: ''
      version_added: 1.1.0
    smtp_config:
      description: SMTP configuration operations on a PowerStore storage system
      name: smtp_config
      namespace: ''
      version_added: 1.5.0
    snapshot:
      description: Manage Snapshots for PowerStore
      name: snapshot
      namespace: ''
      version_added: 1.0.0
    snapshotrule:
      description: Snapshot Rule operations on a PowerStore storage system
      name: snapshotrule
      namespace: ''
      version_added: 1.0.0
    storage_container:
      description: Manage storage container for PowerStore
      name: storage_container
      namespace: ''
      version_added: 2.0.0
    vcenter:
      description: Manage vCenter on a PowerStore storage system
      name: vcenter
      namespace: ''
      version_added: 1.9.0
    volume:
      description: Manage volumes on a PowerStore storage system
      name: volume
      namespace: ''
      version_added: 1.0.0
    volumegroup:
      description: Manage volume groups on a PowerStore Storage System
      name: volumegroup
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 3.4.0
