---
- name: Remote Support Module Operations on Powerstore Array
  hosts: localhost
  connection: local
  vars:
    array_ip: '10.xx.xx.xx'
    validate_certs: false
    user: 'user'
    password: 'Password'

  tasks:
    - name: Get details of remote support configuration
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        state: "present"

    - name: Modify remote support configuration - SRS_Gateway_Tier3
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        support_type: "SRS_Gateway_Tier3"
        remote_support_servers:
          - address: "10.XX.XX.XX"
            port: 9443
            is_primary: true
          - address: "10.XX.XX.YX"
            port: 9443
            is_primary: false
        server_state: "present-in-server"
        is_rsc_enabled: true
        is_cloudiq_enabled: false
        timeout: 300
        state: "present"

    - name: Remove remote support servers
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        support_type: "SRS_Gateway_Tier3"
        remote_support_servers:
          - address: "10.XX.XX.XX"
            port: 9443
            is_primary: true
          - address: "10.XX.XX.XX"
        server_state: "absent-in-server"
        timeout: 300
        state: "present"

    - name: Modify remote support configuration - SRS_Integrated_Tier2
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        support_type: "SRS_Integrated_Tier2"
        proxy_address: "10.XX.XX.XY"
        proxy_port: 3128
        proxy_username: "user"
        proxy_password: "password"
        timeout: 300
        state: "present"

    - name: Verify remote support configuration
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        support_type: "SRS_Integrated_Tier3"
        timeout: 300
        verify_connection: true
        state: "present"

    - name: Send a test alert
      dellemc.powerstore.remote_support:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        remote_support_id: 0
        send_test_alert: true
        state: "present"
