---
- name: SMB Share Module Operations
  hosts: localhost
  connection: local
  vars:
    array_ip: "10.**.**.**"
    validate_certs: false
    user: "user"
    password: "Password"
    share_name: "sample_smb_share"
    filesystem: "ansible_share_fs"
    nas_server: "ansible_nas_server_2"
    snapshot: "sample_snapshot_1"
    share_name_1: "sample_share_1"
    share_name_2: "sample_share_2"

  tasks:
    - name: Create a SMB share for a filesystem
      register: result
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_1 }}"
        filesystem: "{{ filesystem }}"
        path: "/ansible_share_fs/"
        nas_server: "{{ nas_server }}"
        state: "present"

    - name: Create a SMB share for a filesystem Idempotency
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_1 }}"
        filesystem: "{{ filesystem }}"
        path: "/ansible_share_fs/"
        nas_server: "{{ nas_server }}"
        state: "present"

    - name: Create a SMB share for filesystem Snapshot
      register: result
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_2 }}"
        snapshot: "{{ snapshot }}"
        path: "/sample_snapshot_1"
        nas_server: "{{ nas_server }}"
        description: "Share for Snapshot created"
        offline_availability: "PROGRAMS"
        is_continuous_availability_enabled: true
        umask: "027"
        is_branch_cache_enabled: true
        is_abe_enabled: true
        state: "present"

    - name: Create a SMB share for filesystem Snapshot Idempotency
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_2 }}"
        snapshot: "{{ snapshot }}"
        path: "/sample_snapshot_1"
        nas_server: "{{ nas_server }}"
        description: "Share for Snapshot created"
        offline_availability: "PROGRAMS"
        is_continuous_availability_enabled: true
        umask: "027"
        is_branch_cache_enabled: true
        is_abe_enabled: true
        state: "present"

    - name: Create SMB share for a filesystem with ACL
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "sample_smb_share"
        filesystem: "sample_fs"
        nas_server: "{{ nas_server_id }}"
        path: "{{ path }}"
        description: "Sample SMB share created"
        is_abe_enabled: true
        is_branch_cache_enabled: true
        offline_availability: "DOCUMENTS"
        is_continuous_availability_enabled: true
        is_encryption_enabled: true
        acl:
          - access_level: "Full"
            access_type: "Allow"
            trustee_name: "TEST-56\\Guest"
            trustee_type: "User"
            state: "present"
          - access_level: "Read"
            access_type: "Deny"
            trustee_name: "S-1-5-21-8-5-1-32"
            trustee_type: "SID"
            state: "present"
        state: "present"

    - name: Modify Attributes of SMB share for a filesystem with ACL
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "sample_smb_share"
        nas_server: "sample_nas_server"
        description: "Sample SMB share attributes updated"
        is_abe_enabled: false
        is_branch_cache_enabled: false
        offline_availability: "MANUAL"
        is_continuous_availability_enabled: false
        is_encryption_enabled: false
        umask: "022"
        acl:
          - access_level: "Full"
            access_type: "Allow"
            trustee_name: "TEST-56\\Guest"
            trustee_type: "User"
            state: "absent"
          - access_level: "Read"
            access_type: "Deny"
            trustee_name: "S-1-5-21-8-5-1-32"
            trustee_type: "SID"
            state: "absent"
        state: "present"

    - name: Get details of SMB share
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_1 }}"
        filesystem: "{{ filesystem }}"
        nas_server: "{{ nas_server }}"
        state: "present"

    - name: Get details of Snapshot"s SMB share
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_id: "{{ snap_share_id }}"
        state: "present"

    - name: Update a SMB share for filesystem
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_1 }}"
        filesystem: "{{ fs_id }}"
        is_continuous_availability_enabled: true
        is_encryption_enabled: true
        umask: "027"
        is_branch_cache_enabled: true
        is_abe_enabled: true
        state: "present"

    - name: Update a SMB share for a filesystem Idempotency
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_name: "{{ share_name_1 }}"
        filesystem: "{{ fs_id }}"
        is_continuous_availability_enabled: true
        is_encryption_enabled: true
        umask: "027"
        is_branch_cache_enabled: true
        is_abe_enabled: true
        state: "present"

    - name: Delete SMB share (filesystem)
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_id: "{{ fs_share_id }}"
        state: "absent"

    - name: Delete SMB share (filesystem) Idempotency
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_id: "{{ fs_share_id }}"
        state: "absent"

    - name: Delete SMB share (snapshot)
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_id: "{{ snap_share_id }}"
        state: "absent"

    - name: Delete SMB share (snapshot) Idempotency
      dellemc.powerstore.smbshare:
        array_ip: "{{ array_ip }}"
        validate_certs: "{{ validate_certs }}"
        user: "{{ user }}"
        password: "{{ password }}"
        share_id: "{{ snap_share_id }}"
        state: "absent"
