---
- name: Testing vCenter operations on Powerstore
  hosts: localhost
  connection: local
  vars:
    array_ip: "10.**.**.**"
    validate_certs: false
    user: "user"
    password: "Password"

  tasks:
    - name: Add a vcenter
      register: result
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        address: "XX.XX.XX.XX"
        vcenter_username: "user-name"
        vcenter_password: "password"
        update_password: "on_create"
        vasa_provider_credentials:
          username: "admin"
          password: "pass"

    - name: Add a vcenter - Idempotency
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        address: "XX.XX.XX.XX"
        vcenter_username: "user-name"
        vcenter_password: "password"
        update_password: "on_create"
        vasa_provider_credentials:
          username: "admin"
          password: "pass"

    - name: Get details of vCenter
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vcenter_id: "{{ result.vcenter_details.id }}"

    - name: Modify a vCenter attribute
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vcenter_id: "{{ result.vcenter_details.id }}"
        address: "XX.XX.XX.YY"
        vcenter_username: "user-name"
        vcenter_password: "password"
        update_password: "always"

    - name: Modify a vCenter attribute - Idempotency
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vcenter_id: "{{ result.vcenter_details.id }}"
        address: "XX.XX.XX.YY"
        vcenter_username: "user-name"
        vcenter_password: "password"
        update_password: "on_create"

    - name: Remove a vcenter
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vcenter_id: "{{ result.vcenter_details.id }}"
        delete_vasa_provider: true
        state: "absent"

    - name: Remove a vcenter - Idempotency
      dellemc.powerstore.vcenter:
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        vcenter_id: "{{ result.vcenter_details.id }}"
        delete_vasa_provider: true
        state: "absent"
